name: jupy
channels:
  - defaults
  - conda-forge
dependencies:
  - jupyterlab
  - nodejs
  - git
  - tk
  - photutils
  - astroquery
  - spyder
  - autopep8
  - xlrd
  - openpyxl
  - pytables
  - opencv
  - seaborn
  - keras
  - tensorflow
  - selenium
  - beautifulsoup4
  - python-dotenv
  - bokeh
  - ipywidgets
  - ipympl
  - cookiecutter
  - pyscaffoldext-dsproject
